export const GET_ADDRESS = "get_address"
export const GET_CATEGORIES = "get_categories"
export const GET_SHOPS = "get_shops"
export const GET_USER = "get_user"
export const RESET_USER = "reset_user"
export const AUTO_LOGIN = "auto_login"